In [5]:
import sys
sys.path.append("..")
import pandas as pd
from src.benchmark import benchmark, benchmark_rs, get_metrics
from src.data import load_data
from src.features import load_descriptors, build_features, var_scaler
import warnings
from sklearn.exceptions import ConvergenceWarning

warnings.filterwarnings("ignore", category=ConvergenceWarning)

In [2]:
path_data = '../data/suzuki.xlsx'
path_desc = '../data/descriptors.json'
df = load_data(path_data)
descriptors = load_descriptors(path_desc)
df = build_features(df, descriptors)
df = var_scaler(df)

2026-10-04 22:52:48.695 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-10-04 22:52:48.697 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [17]:
test_rs = benchmark_rs(df, n_seeds=1, n_init=10, max_iter=10, rs_runs=100, cutoff_pos=5, cutoff_frac=0.95)

In [18]:
test = benchmark(df, n_seeds=1, n_init=10, max_iter=10, cutoff_pos=5, cutoff_frac=0.95, one_hot=True, prior_values=False)

In [19]:
test_rs.describe()

,iter,seed,best,max_start,max_yield,cutoff_by_pos,cutoff_by_frac
count,15.0,15.0,15.000000,15.000000,15.000000,15.000000,15.000000
mean,1.0,1.0,80.487609,78.406410,90.111261,0.182667,0.356667
std,0.0,0.0,16.932659,17.923501,11.023450,0.227830,0.369685
min,1.0,1.0,34.941975,31.006597,59.077407,0.070000,0.020000
25%,1.0,1.0,72.676244,70.320763,86.497185,0.115000,0.070000
50%,1.0,1.0,86.221728,77.997990,92.528966,0.130000,0.200000
75%,1.0,1.0,93.916345,92.323878,98.196539,0.135000,0.485000
max,1.0,1.0,96.299475,95.845260,100.000000,1.000000,1.000000

In [20]:
combined = pd.concat([test_rs, test], axis=0)

In [21]:
combined[combined["method"]=="rs"]

,method,r1,r2,iter,seed,best,max_start,max_yield,cutoff_by_pos,cutoff_by_frac
0,rs,6-Bromoquinoline,"2a, Boronic Acid",1,1,94.312533,92.884027,97.863652,0.16,0.45
1,rs,6-Bromoquinoline,"2b, Boronic Ester",1,1,86.221728,77.997990,96.746795,0.11,0.19
2,rs,6-Bromoquinoline,"2c, Trifluoroborate",1,1,63.793778,60.483375,74.837727,0.13,0.20
3,rs,6-Iodoquinoline,"2a, Boronic Acid",1,1,94.663033,93.727508,98.692218,0.12,0.52
4,rs,6-Iodoquinoline,"2b, Boronic Ester",1,1,96.299475,95.780276,100.000000,0.07,1.00
5,rs,6-Iodoquinoline,"2c, Trifluoroborate",1,1,75.714108,73.721108,84.773385,0.09,0.11
6,rs,6-Quinolineboronic acid pinacol ester,"2d, Bromide",1,1,78.593716,77.944233,88.220984,0.12,0.03
7,rs,6-chloroquinoline,"2a, Boronic Acid",1,1,89.576419,88.925291,93.674515,0.19,0.21
8,rs,6-chloroquinoline,"2b, Boronic Ester",1,1,91.790635,91.763728,92.528966,1.00,1.00
9,rs,6-chloroquinoline,"2c, Trifluoroborate",1,1,34.941975,31.006597,59.077407,0.13,0.04
10,rs,6-quinoline-boronic acid hydrochloride,"2d, Bromide",1,1,69.807417,66.920418,92.194796,0.13,0.03
11,rs,6-triflatequinoline,"2a, Boronic Acid",1,1,96.093689,95.845260,98.529427,0.12,1.00
12,rs,6-triflatequinoline,"2b, Boronic Ester",1,1,93.520158,91.697680,98.607517,0.13,0.45
13,rs,6-triflatequinoline,"2c, Trifluoroborate",1,1,75.545071,74.649497,84.640446,0.10,0.10
14,rs,Potassium quinoline-6-trifluoroborate,"2d, Bromide",1,1,66.440405,62.749168,91.281082,0.14,0.02